 create table WAFER(
 	WAFER_NO number primary key,
 	section1 number,
 	section2 number,
 	section3 number,
 	section4 number,
 	section5 number,
 	section6 number,
 	section7 number,
 	section8 number,
 	section9 number,
 	section10 number,
 	section11 number,
 	section12 number,
 	section13 number,
 	section14 number,
 	section15 number,
 	section16 number,
 	section17 number,
 	section18 number,
 	section19 number,
 	section20 number,
 	section21 number,
 	section22 number,
 	section23 number,
 	section24 number,
 	section25 number,
  abnormal varchar(2)
 );

